#!/usr/bin/env python

import sys
import numpy as np
import Ska.Numpy

freq, noise, smooth = [float(x) for x in sys.argv[1:]]

size = 1024
x = np.arange(size) * np.pi * freq / 1024.0
y = np.sin(x) + np.sin(1.5 * x + np.pi / 2.) + np.random.normal(0.0, noise, size)

y_sm = Ska.Numpy.smooth(y, smooth)

print 'x y y_smooth'
for x_, y_, y_sm_ in zip(x, y, y_sm):
    print x_, y_, y_sm_

    
